### ISSUE TITLE
ESP-RZXe Support

### ISSUE THREAD

**Issue by StofLE** [homebridge-plugins/homebridge-rainbird#4]
Hi,

i own an ESP-RZXe and got following Log Output:
`DEBUG: Received a response from Rainbird controller
DEBUG: {"serialNumber":"0000000000000000","_type":"SerialNumberResponse"}
DEBUG: Received a response from Rainbird controller
DEBUG: Received a response from Rainbird controller
DEBUG: {"pageNumber":"00","activeStations":"00000000","activeZones":[0,0,0,0],"_type":"CurrentStationsActiveResponse"}
DEBUG: Received a response from Rainbird controller
DEBUG: {"modelID":"0003","protocolRevisionMajor":"02","protocolRevisionMinor":"09","_type":"ModelAndVersionResponse"}
DEBUG: Received a response from Rainbird controller
DEBUG: {"pageNumber":"00","setStations":"3F000000","_type":"AvailableStationsResponse"}`

Stefan

**Comment by iondarie** [comment]
i own the same controller here is my log if it helps with anything:

```
DEBUG: Requesting ModelAndVersionRequest from 192.168.0.18
DEBUG: Sending body: 02
[8/27/2021, 10:08:28 PM] [RainBird] {}
DEBUG: Requesting SerialNumberRequest from 192.168.0.18
DEBUG: Sending body: 05
[8/27/2021, 10:08:28 PM] [RainBird] {}
[8/27/2021, 10:08:28 PM] [RainBird] {"ip":"192.168.0.18","password":"","debug":true}
[8/27/2021, 10:08:28 PM] [RainBird] Adding new accessory: undefined Valve undefined undefined DeviceID: undefined
DEBUG: Requesting SerialNumberRequest from 192.168.0.18
DEBUG: Sending body: 05
DEBUG: Requesting ModelAndVersionRequest from 192.168.0.18
DEBUG: Sending body: 02
[undefined undefined@@Model] characteristic value expected string and received undefined
[undefined undefined@@Serial Number] characteristic value expected string and received undefined
[undefined undefined@@Firmware Revision] characteristic value expected string and received undefined
[undefined undefined@@Firmware Revision] characteristic value expected string and received undefined
DEBUG: Requesting AvailableStationsRequest from 192.168.0.18
DEBUG: Sending body: 0300
DEBUG: Requesting CurrentStationsActiveRequest from 192.168.0.18
DEBUG: Sending body: 3F00
[8/27/2021, 10:08:28 PM] [RainBird] {}
DEBUG: Requesting CurrentStationsActiveRequest from 192.168.0.18
DEBUG: Sending body: 3F00

(node:11195) UnhandledPromiseRejectionWarning: TypeError: getActiveZones.activeZones is not iterable
    at new IrrigationSystem (/homebridge/node_modules/homebridge-rainbird/src/devices/irrigationsystem.ts:82:40)
    at RainbirdPlatform.createValve (/homebridge/node_modules/homebridge-rainbird/src/platform.ts:223:7)
    at RainbirdPlatform.discoverDevices (/homebridge/node_modules/homebridge-rainbird/src/platform.ts:157:16)
    at HomebridgeAPI.<anonymous> (/homebridge/node_modules/homebridge-rainbird/src/platform.ts:62:14)
    at HomebridgeAPI.emit (events.js:412:35)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:11195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

DEBUG: Error during request
Error: 503: Service Unavailable
    at /homebridge/node_modules/homebridge-rainbird/node_modules/node-rainbird/index.js:122:58
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11195) UnhandledPromiseRejectionWarning: Error: 503: Service Unavailable
    at /homebridge/node_modules/homebridge-rainbird/node_modules/node-rainbird/index.js:122:58
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

DEBUG: Received a response from Rainbird controller
DEBUG: {"modelID":"0003","protocolRevisionMajor":"02","protocolRevisionMinor":"09","_type":"ModelAndVersionResponse"}
DEBUG: Error during request
Error: 503: Service Unavailable
    at /homebridge/node_modules/homebridge-rainbird/node_modules/node-rainbird/index.js:122:58
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11195) UnhandledPromiseRejectionWarning: Error: 503: Service Unavailable
    at /homebridge/node_modules/homebridge-rainbird/node_modules/node-rainbird/index.js:122:58
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)

DEBUG: Received a response from Rainbird controller
DEBUG: {"serialNumber":"0000000000000000","_type":"SerialNumberResponse"}

DEBUG: Received a response from Rainbird controller
DEBUG: {"modelID":"0003","protocolRevisionMajor":"02","protocolRevisionMinor":"09","_type":"ModelAndVersionResponse"}
DEBUG: Error during request
Error: 503: Service Unavailable
    at /homebridge/node_modules/homebridge-rainbird/node_modules/node-rainbird/index.js:122:58
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11195) UnhandledPromiseRejectionWarning: Error: 503: Service Unavailable
    at /homebridge/node_modules/homebridge-rainbird/node_modules/node-rainbird/index.js:122:58
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:11195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 16)
DEBUG: Received a response from Rainbird controller
DEBUG: {"pageNumber":"00","activeStations":"02000000","activeZones":[2,0,0,0],"_type":"CurrentStationsActiveResponse"}
```

**Comment by donavanbecker** [comment]
@iondarie, @StofLE, can you guys try the latest beta?

**Comment by iondarie** [comment]
@donavanbecker it seems to work, ill try to do some more tests and come back

**Comment by StofLE** [comment]
> 
> 
> @iondarie, @StofLE, can you guys try the latest beta?

Sure, could you pleas

**Comment by StofLE** [comment]
Clicked wrong...

Seems to work! :-)

**Comment by donavanbecker** [comment]
v0.1.0 is out. When I release v1.0.0 You will have to change your config a little and clear cache on your device to re add it. so don't setup to much automation. Currently you can only add 1 controller in, with v1.0.0 (if you have multiple controllers on one network, rare but possible) you will be able to config more than 1.

**Comment by iondarie** [comment]
@donavanbecker thank you, any chance that the valves could be exposed as sensors? So we can receive notifications when the sprinkler zones’s start

**Comment by mantorok1** [comment]
@iondarie, what type of sensor are you thinking of? Perhaps a leak sensor?

**Comment by donavanbecker** [comment]
> @iondarie, what type of sensor are you thinking of? Perhaps a leak sensor?

We could make this a config option. Let's do this for 1.1.0, we want to get v1.0.0 out first then we can look at this.

**Comment by donavanbecker** [comment]
> @donavanbecker thank you, any chance that the valves could be exposed as sensors? So we can receive notifications when the sprinkler zones’s start

We will track this with #8.

**Comment by donavanbecker** [comment]
v1.0.0 released
