### ISSUE TITLE
Count down timer now gone and getting error "RainBird controller request failed RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5. Received 8]"

### ISSUE THREAD

**Issue by adouglas81** [homebridge-plugins/homebridge-rainbird#57]
### Describe The Bug

No countdown and error. 

### To Reproduce

JUST RUN

### Expected behavior

COUNTDOWN TIMER STAYS NO ERROR

### Relevant log output

```shell
RainBird controller request failed RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5. Received 8]"
```

### Config for homebridge-rainbird

```shell
{
    "name": "RainBird",
    "devices": [
        {
            "ipaddress": "192.168.0.97",
            "password": "PASSWORD"
        }
    ],
    "options": {
        "refreshRate": 120,
        "pushRate": 1
    },
    "_bridge": {
        "username": "0E:76:55:86:C7:F8",
        "port": 33374
    },
    "platform": "RainBird"
}
```

### Device & Model

ESP-ME3

### Node.js Version

14.18

### NPM Version

7.24.1

### Homebridge Version

1.3.4

### Homebridge Rainbird Plugin Version

1.2

### Operating System

MacOS

**Comment by mantorok1** [comment]
Hi @adouglas81, could you set Homebridge into DEBUG mode and restart. Then capture the logs up to the above error message and post here. I suspect the response coming back from the RainBird controller is not what the plugin is expecting.

There is also a new beta version (1.2.1-beta.0) that is out now so you could also try that to see if it helps.

**Comment by adouglas81** [comment]
Thanks for the response here is the log. Also, how do I install he beta. 

```
[10/7/2021, 11:55:10 AM] [homebridge-rainbird] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[10/7/2021, 11:55:10 AM] [homebridge-rainbird] Error: 
    at Model.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Model.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1991:16)
    at Model.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1298:20)
    at AccessoryInformation.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
    at new IrrigationSystem (/usr/local/lib/node_modules/homebridge-rainbird/src/devices/irrigationsystem.ts:47:8)
    at RainbirdPlatform.createIrrigationSystem (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:170:9)
    at RainbirdPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:144:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:61:9)
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Configure Irrigation Service
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Load Valve Service for Zone 1
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Configure Characteristics for Zone 1
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Load Valve Service for Zone 2
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Configure Characteristics for Zone 2
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Load Valve Service for Zone 3
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Configure Characteristics for Zone 3
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Load Valve Service for Zone 4
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Configure Characteristics for Zone 4
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Irrigation System: 9, Active: 0, InUse: 0
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Valve: 1, Active: 0, InUse: 0
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Valve: 2, Active: 0, InUse: 0
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Valve: 3, Active: 0, InUse: 0
[10/7/2021, 11:55:10 AM] [RainBird] [DEBUG] Valve: 4, Active: 0, InUse: 0
[10/7/2021, 11:55:10 AM] [RainBird] Irrigation System UDID: 192.168.0.97-9-02103113500d17
[10/7/2021, 11:55:22 AM] [RainBird] Request: [18] [ControllerDateRequest]
[10/7/2021, 11:55:23 AM] [RainBird] Response: [146,7,167,229] [ControllerDateResponse]
[10/7/2021, 11:55:23 AM] [RainBird] Request: [16] [ControllerTimeRequest]
[10/7/2021, 11:55:23 AM] [RainBird] Response: [144,11,55,17] [ControllerTimeResponse]
[10/7/2021, 11:55:23 AM] [RainBird] Request: [62] [RainSetPointReachedRequest]
[10/7/2021, 11:55:24 AM] [RainBird] Response: [190,0] [RainSetPointReachedResponse]
[10/7/2021, 11:55:24 AM] [RainBird] Request: [72] [IrrigationStateRequest]
[10/7/2021, 11:55:24 AM] [RainBird] Response: [200,1] [IrrigationStateResponse]
[10/7/2021, 11:55:24 AM] [RainBird] Request: [59,0] [CurrentZoneTimeRemainingRequest]
[10/7/2021, 11:55:25 AM] [RainBird] RainBird controller request failed. [RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5. Received 8]
[10/7/2021, 11:55:25 AM] [RainBird] Unable to retrieve controller status
[10/7/2021, 11:55:25 AM] [RainBird] Status timer set for 300 secs
```

**Comment by donavanbecker** [comment]
<a><img src="https://user-images.githubusercontent.com/9875439/136422974-56269916-4a84-4d98-bd82-3ea677fbc5b3.png" width="400px"></a>
<a><img src="https://user-images.githubusercontent.com/9875439/136422973-d6c2f62e-3f44-4df4-9d69-2f3f40f9299f.png" width="300px"></a>
<a><img src="https://user-images.githubusercontent.com/9875439/136422965-64f528c5-c386-4027-a12a-f5d65d47a816.png" width="300px"></a>

**Comment by adouglas81** [comment]
I found it, thanks still kicking out the same error. 

```
[10/7/2021, 12:13:48 PM] [homebridge-rainbird] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[10/7/2021, 12:13:48 PM] [homebridge-rainbird] Error: 
    at Model.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Model.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1991:16)
    at Model.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1298:20)
    at AccessoryInformation.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
    at new IrrigationSystem (/usr/local/lib/node_modules/homebridge-rainbird/src/devices/irrigationsystem.ts:47:8)
    at RainbirdPlatform.createIrrigationSystem (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:172:9)
    at RainbirdPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:145:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:62:9)
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Configure Irrigation Service
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Load Valve Service for Zone 1
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Configure Characteristics for Zone 1
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Load Valve Service for Zone 2
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Configure Characteristics for Zone 2
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Load Valve Service for Zone 3
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Configure Characteristics for Zone 3
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Load Valve Service for Zone 4
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Configure Characteristics for Zone 4
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Irrigation System: 9, Active: 0, InUse: 0
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Valve: 1, Active: 0, InUse: 0
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Valve: 2, Active: 0, InUse: 0
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Valve: 3, Active: 0, InUse: 0
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Valve: 4, Active: 0, InUse: 0
[10/7/2021, 12:13:48 PM] [RainBird] Irrigation System UDID: 192.168.0.97-9-02103113500d17
[10/7/2021, 12:13:48 PM] [RainBird] Restoring existing accessory from cache: WR2
[10/7/2021, 12:13:48 PM] [RainBird] [DEBUG] Configure Leak Sensor Service
[10/7/2021, 12:13:48 PM] [RainBird] Leak Sensor UDID: 192.168.0.97-WR2-02103113500d17
[10/7/2021, 12:14:03 PM] [RainBird] Request: [59,0] [CurrentZoneStateRequest]
[10/7/2021, 12:14:03 PM] [RainBird] RainBird controller request failed. [RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 5. Received 8]
[10/7/2021, 12:14:03 PM] [RainBird] Request: [62] [RainSensorStateRequest]
[10/7/2021, 12:14:03 PM] [RainBird] Response: [190,0] [RainSensorStateResponse]
[10/7/2021, 12:14:03 PM] [RainBird] Status timer set for 300 secs
```

**Comment by mantorok1** [comment]
Hi @adouglas81, thanks for the logs. That has pinpointed which request is causing the issue but unfortunately it doesn't show the response coming back. I've just pushed a new change (version 1.2.1-beta.2) that will include the response in an error message.

Could you please upgrade to this version and post the new error message you should see in the logs.  Thanks

Be aware that I may need you to run this a few times under different scenarios to help reverse engineer the response from your controller. They don't seem to be documented anywhere.

**Comment by adouglas81** [comment]
Thanks for all your efforts. See below. 

Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 186-41-785 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 19D7 5680' using bonjour-hap backend!
[10/7/2021, 5:47:13 PM] Homebridge v1.3.4 (Homebridge 19D7) is running on port 51662.
Initializing HAP-NodeJS v0.9.4...
Initializing HAP-NodeJS v0.9.4...
Initializing HAP-NodeJS v0.9.4...

[10/7/2021, 5:47:13 PM] [RainBird] Loaded homebridge-rainbird v1.2.1-beta.2 child bridge successfully
[10/7/2021, 5:47:13 PM] Loaded 2 cached accessories from cachedAccessories.0E8A39EE43B8.
[10/7/2021, 5:47:13 PM] [RainBird] [DEBUG] Finished initializing platform:
[10/7/2021, 5:47:13 PM] [RainBird] [DEBUG] Config OK
[10/7/2021, 5:47:13 PM] [RainBird] Loading accessory from cache: 9
[10/7/2021, 5:47:13 PM] [RainBird] Loading accessory from cache: WR2
Preparing Advertiser for 'RainBird E36B' using bonjour-hap backend!
[10/7/2021, 5:47:13 PM] [RainBird] Executed didFinishLaunching callback
[10/7/2021, 5:47:13 PM] [RainBird] Init
[10/7/2021, 5:47:13 PM] [RainBird] Request: [2] [ModelAndVersionRequest]
Starting to advertise 'RainBird E36B' using bonjour-hap backend!
[10/7/2021, 5:47:13 PM] Homebridge v1.3.4 (RainBird) is running on port 53908.
[10/7/2021, 5:47:13 PM] Registering platform 'homebridge-ring.Ring'
[10/7/2021, 5:47:13 PM] [homebridge-ring] Loaded homebridge-ring v9.22.0 child bridge successfully
[10/7/2021, 5:47:13 PM] Loaded 3 cached accessories from cachedAccessories.0E6917344498.
[10/7/2021, 5:47:13 PM] [RainBird] Response: [130,0,9,2,12] [ModelAndVersionResponse]
[10/7/2021, 5:47:13 PM] [RainBird] Request: [5] [SerialNumberRequest]

[10/7/2021, 5:47:16 PM] [RainBird] Response: [133,2,16,49,19,80,13,23,146] [SerialNumberResponse]
[10/7/2021, 5:47:16 PM] [RainBird] Request: [3,0] [AvailableZonesRequest]
[10/7/2021, 5:47:16 PM] [RainBird] Response: [131,0,15,0,0,0] [AvailableZonesResponse]
[10/7/2021, 5:47:16 PM] [RainBird] Request: [72] [IrrigationStateRequest]
[10/7/2021, 5:47:16 PM] [RainBird] Response: [200,1] [IrrigationStateResponse]
[10/7/2021, 5:47:16 PM] [RainBird] Request: [18] [ControllerDateRequest]
[10/7/2021, 5:47:16 PM] [RainBird] Response: [146,7,167,229] [ControllerDateResponse]
[10/7/2021, 5:47:16 PM] [RainBird] Request: [16] [ControllerTimeRequest]


[10/7/2021, 5:47:18 PM] [RainBird] Response: [144,17,47,9] [ControllerTimeResponse]
[10/7/2021, 5:47:18 PM] [RainBird] Request: [59,0] [CurrentZoneStateRequest]
[10/7/2021, 5:47:21 PM] [RainBird] RainBird controller request failed. [Error: Invalid response: [187,0,0,0,0,0,0] [CurrentZoneStateResponse]]
[10/7/2021, 5:47:21 PM] [RainBird] Request: [62] [RainSensorStateRequest]
[10/7/2021, 5:47:21 PM] [RainBird] Response: [190,0] [RainSensorStateResponse]
[10/7/2021, 5:47:21 PM] [RainBird] Status timer set for 300 secs
[10/7/2021, 5:47:21 PM] [RainBird] Model: 9, [Version: 2.12, Serial Number: 02103113500d17, Zones: [1,2,3,4]]
[10/7/2021, 5:47:21 PM] [RainBird] Restoring existing accessory from cache: 9
[10/7/2021, 5:47:21 PM] [homebridge-rainbird] This plugin generated a warning from the characteristic 'Model': [Model] characteristic must have a length of more than 1 character otherwise HomeKit will reject this accessory, ignoring new value. See https://git.io/JtMGR for more info.
[10/7/2021, 5:47:21 PM] [homebridge-rainbird] Error: 
    at Model.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at Model.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1991:16)
    at Model.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1298:20)
    at AccessoryInformation.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
    at new IrrigationSystem (/usr/local/lib/node_modules/homebridge-rainbird/src/devices/irrigationsystem.ts:47:8)
    at RainbirdPlatform.createIrrigationSystem (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:172:9)
    at RainbirdPlatform.discoverDevices (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:145:12)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:62:9)
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Configure Irrigation Service
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Load Valve Service for Zone 1
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Configure Characteristics for Zone 1
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Load Valve Service for Zone 2
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Configure Characteristics for Zone 2
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Load Valve Service for Zone 3
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Configure Characteristics for Zone 3
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Load Valve Service for Zone 4
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Configure Characteristics for Zone 4
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Irrigation System: 9, Active: 0, InUse: 0
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Valve: 1, Active: 0, InUse: 0
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Valve: 2, Active: 0, InUse: 0
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Valve: 3, Active: 0, InUse: 0
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Valve: 4, Active: 0, InUse: 0
[10/7/2021, 5:47:21 PM] [RainBird] Irrigation System UDID: 192.168.0.97-9-02103113500d17
[10/7/2021, 5:47:21 PM] [RainBird] Restoring existing accessory from cache: WR2
[10/7/2021, 5:47:21 PM] [RainBird] [DEBUG] Configure Leak Sensor Service
[10/7/2021, 5:47:21 PM] [RainBird] Leak Sensor UDID: 192.168.0.97-WR2-02103113500d17
[10/7/2021, 5:47:34 PM] [RainBird] Request: [59,0] [CurrentZoneStateRequest]
[10/7/2021, 5:47:34 PM] [RainBird] RainBird controller request failed. [Error: Invalid response: [187,0,0,0,0,0,0] [CurrentZoneStateResponse]]
[10/7/2021, 5:47:34 PM] [RainBird] Request: [62] [RainSensorStateRequest]
[10/7/2021, 5:47:34 PM] [RainBird] Response: [190,0] [RainSensorStateResponse]
[10/7/2021, 5:47:34 PM] [RainBird] Status timer set for 300 secs

**Comment by mantorok1** [comment]
Awesome, thanks @adouglas81

This is the one I'm interested in:
```
RainBird controller request failed. [Error: Invalid response: [187,0,0,0,0,0,0] [CurrentZoneStateResponse]]
```
Can you confirm that at the time this error occurred your RainBird was not actively watering a zone.

Could you also use the app to manually start the watering for zone 1 and then restart homebridge and post the above error. Take note of the (approx) time remaining from the app and let me know that too.

Then do the same again for zone 2.

**Comment by adouglas81** [comment]
Confirm that there was  no active watering at the time of the prior error
message provided .

Set Zone 1 to a 5 min manual watering, restarted homebridge, with about
4 min and some seconds remaining.  Received the following error.
[10/7/2021, 6:04:00 PM] [RainBird] RainBird controller request failed.
[Error: Invalid response: [187,0,4,1,0,0,0] [CurrentZoneStateResponse]]

**Comment by mantorok1** [comment]
Could you please do the same again for zone 2

**Comment by adouglas81** [comment]
Zone 2 set for 5 min, under 3 left.


[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Configure Irrigation Service
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Load Valve Service for Zone 1
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Configure Characteristics for
Zone 1
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Load Valve Service for Zone 2
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Configure Characteristics for
Zone 2
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Load Valve Service for Zone 3
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Configure Characteristics for
Zone 3
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Load Valve Service for Zone 4
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Configure Characteristics for
Zone 4
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Irrigation System: 9, Active: 0,
InUse: 0
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Valve: 1, Active: 0, InUse: 0
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Valve: 2, Active: 0, InUse: 0
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Valve: 3, Active: 0, InUse: 0
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Valve: 4, Active: 0, InUse: 0
[10/7/2021, 6:28:20 PM] [RainBird] Irrigation System UDID:
192.168.0.97-9-02103113500d17
[10/7/2021, 6:28:20 PM] [RainBird] Restoring existing accessory from cache:
WR2
[10/7/2021, 6:28:20 PM] [RainBird] [DEBUG] Configure Leak Sensor Service
[10/7/2021, 6:28:20 PM] [RainBird] Leak Sensor UDID:
192.168.0.97-WR2-02103113500d17
[10/7/2021, 6:28:22 PM] [RainBird] Request: [59,0] [CurrentZoneStateRequest]
[10/7/2021, 6:28:22 PM] [RainBird] RainBird controller request failed.
[Error: Invalid response: [187,0,4,1,0,0,0] [CurrentZoneStateResponse]]
[10/7/2021, 6:28:22 PM] [RainBird] Request: [62] [RainSensorStateRequest]
[10/7/2021, 6:28:22 PM] [RainBird] Response: [190,0]
[RainSensorStateResponse]
[10/7/2021, 6:28:22 PM] [RainBird] Status timer set for 300 secs





>

**Comment by mantorok1** [comment]
Hmm, so for zone 1 and 2 you are getting the same response:
```
[187,0,4,1,0,0,0]
```
So it looks like this is not telling us what is the active zone and and how much time is remaining like it does for other models. I'm a bit stumped now

**Comment by adouglas81** [comment]
The Model is the ESP-ME3.

**Comment by mantorok1** [comment]
I have the ESP-TM2.
Have you tried version 1.0.0 of the plugin? It used a different command to obtain the zone and time remaining but it didn't work for the ESP-RZXe model

**Comment by adouglas81** [comment]
V.1.0.0 did not work, 
However, v.0.1.0 seems to work fine. Do you think there is anyway to make it work
with the new versions as they come out?

**Comment by mantorok1** [comment]
Yeah, version 0.1.0 doesn't request the current zone and time remaining from the controller so I would expect it to work. It won't, however, show if a zone is active because a program is running or you manually started it from the app.

The only thing I can suggest is that you try to do something like @tu00tf did in https://github.com/donavanbecker/homebridge-rainbird/issues/39 to capture the requests from and responses to the app, but it could be quite technical.

It's interesting that the ESP-MEI model (that @tu00tf has) has a different API to the ESP-ME3 model. I thought they are all part of the ESP-ME series of controllers.

There's no firmware update available for your model is there?

**Comment by adouglas81** [comment]
No firmware available, I will take a look at #39 and see what I can provide.

**Comment by mantorok1** [comment]
Hi @adouglas81, can you try the new beta (1.2.1-beta.3) and see if it works better for you. It uses a different command (3F) to get the active zone but it's not possible to get the time remaining or if the zone is actually running so it will have a couple of limitations:
- it won't be possible to show the time remaining for a zone that was not started via the plugin (such as a scheduled program). The time remaining will show as 00:00 in these cases
- a zone will show as active even though a scheduled program has been suspended (due to rain)

**Comment by adouglas81** [comment]
It is working without error, and with the limitations you described. Thank
you for your efforts on this.

**Comment by mantorok1** [comment]
That's great news. Please let me know if you do find an API call that can return the time remaining and I'll include it in the plugin in a future version.

**Comment by adouglas81** [comment]
I hope that someone else could assist with that .

**Comment by donavanbecker** [comment]
V1.3.0 is released.
