### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by flipit** [homebridge-plugins/homebridge-rainbird#88]
### Describe The Bug

TypeError:Cannot read property 'debug'  of undefined  at RainbirdPlatform.debug (ts:321:30)

### To Reproduce

Upgrade to v1.4.0

### Expected behavior

 "Logging Settings"  in the Plugin Settings doesn't provide a way to select 'Device' or 'Debug'  and should.

### Relevant log output

```shell
I had to manually add 'options' 'debug' (true/false) to the config file to avoid the TypeError and SigTerm shutdown.
```

### Config for homebridge-rainbird

```shell
"options": {
"debug":false
},
```

### Device & Model

N/A

### Node.js Version

V14.18.1

### NPM Version

v6.14.15

### Homebridge Version

v1.3.5

### Homebridge Rainbird Plugin Version

v1.4.0

### Operating System

Raspbian GNU/ Linux Buster (10)

**Comment by donavanbecker** [comment]
@flipit, sorry I will get that fixed.

Do you have logs?

**Comment by flipit** [comment]
[30/10/2021, 15:41:47] [RainBird] Initializing RainBird platform...
[30/10/2021, 15:41:47] TypeError: Cannot read property 'debug' of undefined
    at RainbirdPlatform.debug (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:321:30)
    at new RainbirdPlatform (/usr/local/lib/node_modules/homebridge-rainbird/src/platform.ts:30:10)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[30/10/2021, 15:41:47] Got SIGTERM, shutting down Homebridge...

I noticed that if use the homebridge UI from chrome on laptop that the options are available and do write to the config file whereas from iOS Safari the list is not selectable. It's the option 'None' that is causing the issue, if there's no "options": {"debug": ....} in the json is causes the TypeError.

**Comment by donavanbecker** [comment]
@flipit can you try the latest beta?

**Comment by flipit** [comment]
That fixes it.

'Logging Settings" in the UI set to 'None' , no 'options' written to the config.  iOS Safari now shows the drop down selection also.

Config ------

            "name": "RainBird",
            "devices": [
                {
                    "ipaddress": "xxxxxxxxxxx",
                    "password": "xxxxxxxxxxx",
                    "showValveSensor": true
                }
            ],
            "platform": "RainBird"


Logs -----

[31/10/2021, 08:07:47] [RainBird] Model: ESP-Me, [Version: 2.9, Serial Number: 4231a7e8841a00, Zones: [1,2,3,4,5,6,7]]
[31/10/2021, 08:07:47] [RainBird] Restoring existing accessory from cache: ESP-Me
[31/10/2021, 08:07:47] [RainBird] Restoring existing accessory from cache: ESP-Me-1
[31/10/2021, 08:07:47] [RainBird] Restoring existing accessory from cache: ESP-Me-2
[31/10/2021, 08:07:47] [RainBird] Restoring existing accessory from cache: ESP-Me-3
[31/10/2021, 08:07:47] [RainBird] Restoring existing accessory from cache: ESP-Me-4
[31/10/2021, 08:07:47] [RainBird] Restoring existing accessory from cache: ESP-Me-5
[31/10/2021, 08:07:47] [RainBird] Restoring existing accessory from cache: ESP-Me-6
[31/10/2021, 08:07:48] [RainBird] Restoring existing accessory from cache: ESP-Me-7
